run:
  timeout: 5m
  skip-dirs:
    - cached-deps
  build-tags:
    - k8s
    - unit_test
linters:
  enable:
    - wrapcheck
    - nolintlint
    - gofmt
linters-settings:
  errcheck:
    exclude-functions:
      - (*database/sql.Tx).Rollback
      - (*github.com/spf13/cobra.Command).MarkFlagCustom
      - (*github.com/spf13/cobra.Command).Usage
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: false
    require-specific: true
  wrapcheck:
    ignoreSigs:
      - github.com/pachyderm/pachyderm/v2/src/internal/errors.Errorf
      - github.com/pachyderm/pachyderm/v2/src/internal/errors.New
      - github.com/pachyderm/pachyderm/v2/src/internal/errors.Unwrap
      - github.com/pachyderm/pachyderm/v2/src/internal/errors.EnsureStack
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
    ignorePackageGlobs:
      # These are packages whose return values don't have to be wrapped, not packages where the
      # linter isn't used.
      - github.com/pachyderm/pachyderm/v2/src/*
    ignoreInterfaceRegexps:
      - ^fileset\.
      - ^collection\.
      - ^track\.
  gofmt:
    simplify: true
