{{- /* This is only for testing; you won't want to put your private key material in values.yaml */ -}}
{{- if and .Values.proxy.tls.secret.key .Values.proxy.tls.secret.cert -}}
apiVersion: v1
kind: Secret
metadata:
  name: pachyderm-proxy-tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{ .Values.proxy.tls.secret.cert | indent 4 }}
  tls.key: |
{{ .Values.proxy.tls.secret.key | indent 4 }}
{{- end }}
