pachd:
  securityContext:
    enabled: false
  storage:
    minio:
      endpoint: "minio.pach-test.svc.cluster.local:9000"

etcd:
  securityContext:
    enabled: false
  resources:
    requests:
      cpu: 250m
      memory: 512M

postgresql:
  enabled: true
  service:
    type: NodePort
  securityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  persistence:
    enabled: false
