# SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
# SPDX-License-Identifier: Apache-2.0
deployTarget: custom

pachd:
  image:
    tag: 3060a3bd07de6c26a8a2ff711c85164c1a246687
  resources:
    requests:
      cpu: 250m
      memory: 512M
  service:
    type: NodePort
  metrics:
    enabled: false
  clusterDeploymentID: dev
  # pachAuthClusterRoleBindings:
  #   allClusterUsers:
  #     ["debugger", "projectOwner", "projectCreator", "repoOwner", "robotUser", "secretAdmin", "pachdLogReader"]
  # to enable enterprise features pass in pachd.activateEnterprise=true, and a valid pachd.enterpriseLicenseKey
  activateEnterprise: true
  additionalTrustedPeers:
    - console-local
  rootToken: "pizza"
  enterpriseLicenseKey: ""
  oauthRedirectURI: "http://localhost:8283/authorization-code/callback"
  storage:
    backend: MINIO
    minio:
      bucket: "pachyderm-test"
      endpoint: "minio.default.svc.cluster.local:9000"
      id: "minioadmin"
      secret: "minioadmin"
      secure: "false"
      signature: ""

proxy:
  enabled: true
  host: localhost:8283
  service:
    type: LoadBalancer
    httpPort: 8283

etcd:
  service:
    type: NodePort

postgresql:
  service:
    type: NodePort
    
console:
  enabled: true
  image:
    tag: ba12ac3ef3f6ea537ca5bf32f0f225a361a2a18a 
  config:  
    oauthRedirectURI: http://localhost:8283/oauth/callback/?inline=true 
    oauthClientSecret: "123"
    disableTelemetry: true

oidc:
  issuerURI: "http://pachd.default.svc.cluster.local:30658/dex"
  userAccessibleOauthIssuerHost: "http://localhost:8283"
  # additionalClients:
  #   - id: console-local
  #     name: console-local
  #     secret: "123"
  #     redirect_uris:
  #       - http://localhost:4000/oauth/callback/?inline=true
  #   - id: determined-local
  #     name: determined-local
  #     secret: "123"
  #     redirect_uris:
  #       - http://localhost:8282/oauth/callback/?inline=true # - http://determined-master-service-pachyderm.default.svc.cluster.local:8282

# determined:
#   imageRegistry: registry-1.docker.io/determinedai
#   maxSlotsPerPod: 0
#   enabled: true
#   enterpriseEdition: true
#   useNodePortForMaster: false
#   useNodePortForDB: false
#   detVersion: 0.23.1
#   masterPort: 8282
#   oidc:
#     enabled: true 
#     idpRecipientUrl: http://localhost:8282
#   #   # idpSsoUrl: "http://localhost:8283" #"http://pachd.default.svc.cluster.local:30658/dex"
#     clientId: "determined-local"
  #   clientSecret: "123"
 