# SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
# SPDX-License-Identifier: Apache-2.0
deployTarget: custom

pachd:
  image:
    tag: local
  resources:
    requests:
      cpu: 250m
      memory: 512M
  service:
    type: NodePort
  metrics:
    enabled: false
  clusterDeploymentID: dev
  pachAuthClusterRoleBindings:
    allClusterUsers:
      ["debugger", "projectOwner", "projectCreator", "repoOwner", "robotUser", "secretAdmin", "pachdLogReader"]
  # to enable enterprise features pass in pachd.activateEnterprise=true, and a valid pachd.enterpriseLicenseKey
  activateEnterprise: true
  additionalTrustedPeers:
    - console-local
  rootToken: "pizza"
  enterpriseLicenseKey: ""
  oauthRedirectURI: "http://localhost:8283/authorization-code/callback"
  storage:
    backend: MINIO
    minio:
      bucket: "pachyderm-test"
      endpoint: "minio.default.svc.cluster.local:9000"
      id: "minioadmin"
      secret: "minioadmin"
      secure: "false"
      signature: ""

proxy:
  enabled: true
  host: localhost:8283
  service:
    type: LoadBalancer
    httpPort: 8283

etcd:
  service:
    type: NodePort

postgresql:
  service:
    type: NodePort
    
console:
  enabled: true
  image:
    tag: 49648661011fa26986a6f71ffabe77d1f286eef3 
  config:  
    oauthRedirectURI: http://localhost:8283/oauth/callback/?inline=true 
    oauthClientSecret: "123"
    disableTelemetry: true

oidc:
  issuerURI: "http://pachd.default.svc.cluster.local:30658/dex"
  userAccessibleOauthIssuerHost: "http://localhost:8283"
  

 