{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if .Values.enterpriseServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "1656"
    prometheus.io/scrape: "true"
  labels:
    app: pach-enterprise
    suite: pachyderm
    {{- if .Values.enterpriseServer.service.labels }}
    {{- toYaml .Values.enterpriseServer.service.labels | nindent 4 }}
    {{- end }}
  name: pach-enterprise
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: api-grpc-port
    # TODO: can we start serving enterprise server on 31650?
    {{- if eq .Values.enterpriseServer.service.type "NodePort" }}
<<<<<<< HEAD
    nodePort: {{ .Values.enterpriseServer.service.apiGRPCPort }}
    {{- end }}
    port: {{ .Values.enterpriseServer.service.apiGRPCPort }}
=======
    nodePort: {{ .Values.enterpriseServer.service.port }}
    {{- end }}
    port: {{ .Values.enterpriseServer.service.port }}
>>>>>>> 504264a37f (Making ports flexible and such)
    protocol: TCP
    targetPort: api-grpc-port
  - name: oidc-port
    {{- if eq .Values.enterpriseServer.service.type "NodePort" }}
<<<<<<< HEAD
    nodePort: {{ .Values.enterpriseServer.service.oidcPort }}
    {{ end }}
    port: {{ .Values.enterpriseServer.service.oidcPort }}
    targetPort: oidc-port
  - name: identity-port
    {{- if eq .Values.enterpriseServer.service.type "NodePort" }}
    nodePort: {{ .Values.enterpriseServer.service.identityPort }}
    {{ end }}
    port: {{ .Values.enterpriseServer.service.identityPort }}
    targetPort: identity-port
  - name: prom-metrics
    {{- if eq .Values.enterpriseServer.service.type "NodePort" }}
    nodePort: {{ .Values.enterpriseServer.service.prometheusPort }}
    {{- end }}
    port: {{ .Values.enterpriseServer.service.prometheusPort }}
=======
    nodePort: {{ add .Values.enterpriseServer.service.port 7 }}
    {{- end }}
    port: {{ add .Values.enterpriseServer.service.port 7 }}
    targetPort: oidc-port
  - name: identity-port
    {{- if eq .Values.enterpriseServer.service.type "NodePort" }}
    nodePort: {{ add .Values.enterpriseServer.service.port 8 }}
    {{- end }}
    port: {{ add .Values.enterpriseServer.service.port 8 }}
    targetPort: identity-port
  - name: prom-metrics
    {{- if eq .Values.enterpriseServer.service.type "NodePort" }}
    nodePort: {{ add .Values.enterpriseServer.service.port 6 }}
    {{- end }}
    port: {{ add .Values.enterpriseServer.service.port 6 }}
>>>>>>> 504264a37f (Making ports flexible and such)
    protocol: TCP
    targetPort: prom-metrics
  selector:
    app: pach-enterprise
  type: {{ .Values.enterpriseServer.service.type }}
{{- end }}
