apiVersion: v1
kind: Pod
metadata:
    labels:
        run: nginx
        suite: pachyderm
        app: nginx
    name: nginx
    namespace: default
spec:
    containers:
        - image: nginx
          name: nginx
          resources: {}
          ports:
              - containerPort: 80
